title:        "Parth's Blog"
tagline:      "Parth's Blog"
description:  'About Programming etc ..'
url:          http://parthpatil.com
home:         '/'
version:      1.0.0
author:
  name:       'Parth Patil'
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  pygments 
plugins: [jekyll-paginate]
paginate:     2
