title:        "Parth's Blog"
tagline:      'My Tagline'
description:  'Programming blog'
url:          http://parthpatil.com
home:         '/'
version:      1.0.0
author:
  name:       'Parth Patil'
  email:      ''
markdown:     rdiscount
permalink:    pretty
pygments:     true
paginate:     2
