title:        "Parth's Blog"
tagline:      'My Tagline'
description:  'About Programming etc ..'
url:          http://parthpatil.com
home:         '/'
version:      1.0.0
author:
  name:       'Parth Patil'
  email:      ''
markdown:     rdiscount
permalink:    pretty
highlighter:  rouge
paginate:     2
